import { HomeIcon } from "@heroicons/react/solid";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import HeaderIcon from "../components/HeaderIcon";
import Login from "../components/Login";
import { getSession } from "next-auth/react";
import Sidebar from "../components/Sidebar";

export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>pyNotes</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>

      {/* Header */}
      <Header />
      <main>
        <Sidebar />
        {/* Feed */}
        {/* Widgets */}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  // get the user
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
